name: Run BATS tests
description: Execute the repository's BATS test suite.
inputs:
  bats-arguments:
    description: Additional arguments to pass to the bats command.
    required: false
    default: -r tests
  args:
    description: Optional alias for bats-arguments.
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Install bats
      shell: bash
      run: |
        set -euo pipefail
        sudo apt-get update -y
        sudo apt-get install -y --no-install-recommends bats
        sudo rm -rf /var/lib/apt/lists/*
    - name: Run bats
      shell: bash
      env:
        PRIMARY_ARGS: ${{ inputs.bats-arguments }}
        ALIAS_ARGS: ${{ inputs.args }}
      run: |
        set -euo pipefail
        args="${ALIAS_ARGS:-}"
        if [[ -z "$args" ]]; then
          args="$PRIMARY_ARGS"
        fi
        if [[ -z "$args" ]]; then
          echo "Error: No test files or directories specified for bats. Please provide arguments via 'bats-arguments' or 'args'."
          exit 1
        else
          # shellcheck disable=SC2086  # Allow intentional word splitting for bats args.
          bats $args
        fi
