name: contracts-validate
permissions:
  contents: read
  actions: read
  checks: write
on: [push, pull_request]
jobs:
  validate:
    uses: heimgewebe/metarepo/.github/workflows/contracts-validate.yml@contracts-v1
