name: security
permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: '0 5 * * *'
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: security-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      # Caches beschleunigen cargo-audit merklich
      - name: Cache cargo registry + advisory DB
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/advisory-db
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # Use pre-built action for cargo-audit to avoid repeated compilation
      - name: Audit dependencies
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      # Optional: falls du ein eigenes DB-Verzeichnis nutzt
      # - name: Audit with explicit DB path
      #   run: cargo audit -d ~/.cargo/advisory-db
